---
title: "badmapProjectOnlinePlots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##data wrangling packages (most part of the tidyverse)
library(stringr)
library(reshape2)
library(ggplot2)##plotting
library(plyr)
library(dplyr)
library(tidyr)
library(forcats)
library(scales)
library(modelbased)

#fonts
library(extrafont)
#font_import()
loadfonts(device = "win")




##analyses packages
library(lmerTest)
library(lme4)


options(scipen=1, digits=3)

```

#Load the data

##noun task, id task, baseline
```{r}
nounTask_OnlineGdFinal<-read.csv("nounOnlineResultsGood.csv", header=TRUE, stringsAsFactors = FALSE)

ddply(nounTask_OnlineGdFinal, .(condition), summarize, NumSubjects = length(unique(subject)))


idTask_OnlineGdFinal<-read.csv("idOnlineResultsGood.csv", header=TRUE, stringsAsFactors = FALSE)

sampleSize<-ddply(idTask_OnlineGdFinal, .(condition), summarize, NumSubjects = length(unique(subject)))

```




##FIGURES: 

###NOUN NOT NOUN:  


```{r, echo=FALSE}

nnnMean_final<- aggregate(nounAnswer~wordType+subject+condition,nounTask_OnlineGdFinal, FUN="mean")
nnnMean_final_group<- aggregate(nounAnswer~wordType+condition,nounTask_OnlineGdFinal, FUN="mean")


ggplot(nnnMean_final_group, aes(wordType, nounAnswer))+
  geom_bar(stat = "identity", position="dodge", aes(fill=condition))+
#  geom_errorbar(aes(ymin=Button.Pressed-sem, ymax=Button.Pressed+sem, shape=Condition), width=.2,size=1, position=position_dodge(.9))+
  geom_point(data = nnnMean_final, position =position_jitterdodge(jitter.width = 0,jitter.height = 0,dodge.width = .9), aes(x = wordType, y = nounAnswer, shape = condition),alpha=.3, size=2)+
  scale_fill_manual(values=c("#005a9c","#bf2c37","#008061","#b9ae35"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map"))+
    scale_shape_discrete(labels=c("Early Ambiguous","Early Bad Map", "Late Ambiguous", "Late Bad Map"))+
  ylab("Percent 'NOUN' answer")+
  xlab("Word type")+
  ylim(0,1)+
  theme_minimal(base_size = 20)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        text = element_text(family="Arial"),
        legend.position="right",
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        plot.title = element_text(size=16))

```

```{r}

SHres <- aggregate(SAnswer~step+condition, idTask_OnlineGdFinal, FUN="mean")

SHres_sd<-aggregate(SAnswer~step+condition, idTask_OnlineGdFinal, FUN="sd")

SHres$sd<-SHres_sd$SAnswer

idAverage<-merge(sampleSize, SHres)

idAverage$sem<-idAverage$sd/sqrt(idAverage$NumSubjects)

idAverage$conditionType[idAverage$condition %in% c("aam","bam")]<-"Ambiguous Conditions"
idAverage$conditionType[idAverage$condition %in% c("abm","bbm","baseline")]<-"Bad Map Conditions"

idAverage$step<-factor(idAverage$step)

png("Exp1Online2.png", units="in", width=12, height=6, res=300)


ggplot(idAverage, aes(step, SAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage,aes(ymin=SAnswer-sem,ymax=SAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005a9c","#bf2c37","#A5FFD6","#001f23","#b9ae35"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Baseline","Late Bad Map"))+
      theme_minimal(base_size = 14)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        plot.title = element_text(size=12),
        text = element_text(family="Times New Roman"))+
        guides(linetype=FALSE)+
        facet_wrap(~conditionType)

dev.off()


```

##EARLY PASSES

```{r}
idTask_OnlineGdFinalEARLY<-idTask_OnlineGdFinal[idTask_OnlineGdFinal$phase %in% c("Early"),]

SHresERL <- aggregate(SAnswer~step+condition, idTask_OnlineGdFinalEARLY, FUN="mean")

SHresERL_sd<-aggregate(SAnswer~step+condition, idTask_OnlineGdFinalEARLY, FUN="sd")

SHresERL$sd<-SHresERL_sd$SAnswer

idAverageERL<-merge(sampleSize, SHresERL)

idAverageERL$sem<-idAverageERL$sd/sqrt(idAverageERL$NumSubjects)

idAverageERL$conditionType[idAverageERL$condition %in% c("aam","bam")]<-"Ambiguous Conditions"
idAverageERL$conditionType[idAverageERL$condition %in% c("abm","bbm","baseline")]<-"Bad Map Conditions"

idAverageERL$step<-factor(idAverageERL$step)

png("earlyAmbigExp1OnlineEARLY2.png", units="in", width=12, height=6, res=300)


ggplot(idAverageERL, aes(step, SAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverageERL,aes(ymin=SAnswer-sem,ymax=SAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005a9c","#bf2c37","#A5FFD6","#001f23","#b9ae35"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Baseline","Late Bad Map"))+
      theme_minimal(base_size = 14)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        plot.title = element_text(size=12),
        text = element_text(family="Times New Roman"))+
  guides(linetype=FALSE)+
  facet_wrap(~conditionType)

dev.off()

```

##LATE PASSES

```{r}
idTask_OnlineGdFinalLATE<-idTask_OnlineGdFinal[idTask_OnlineGdFinal$phase %in% c("Late"),]

SHresLT <- aggregate(SAnswer~step+condition, idTask_OnlineGdFinalLATE, FUN="mean")

SHresLT_sd<-aggregate(SAnswer~step+condition, idTask_OnlineGdFinalLATE, FUN="sd")

SHresLT$sd<-SHresLT_sd$SAnswer

idAverageLT<-merge(sampleSize, SHresLT)

idAverageLT$sem<-idAverageLT$sd/sqrt(idAverageLT$NumSubjects)

idAverageLT$conditionType[idAverageLT$condition %in% c("aam","bam")]<-"Ambiguous Conditions"
idAverageLT$conditionType[idAverageLT$condition %in% c("abm","bbm","baseline")]<-"Bad Map Conditions"

idAverageLT$step<-factor(idAverageLT$step)

png("Exp1OnlineLATE2.png", units="in", width=12, height=6, res=300)


ggplot(idAverageLT, aes(step, SAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverageLT,aes(ymin=SAnswer-sem,ymax=SAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005a9c","#bf2c37","#A5FFD6","#001f23","#b9ae35"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Baseline","Late Bad Map"))+
      theme_minimal(base_size = 14)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        plot.title = element_text(size=12),
        text = element_text(family="Times New Roman"))+
  guides(linetype=FALSE)+
    facet_wrap(~conditionType)


dev.off()


```


```{r}

##plots for psychonomics' 

idAverageERL$conditionType[idAverageERL$condition %in% c("bam")]<-"a"
idAverageERL$conditionType[idAverageERL$condition %in% c("aam")]<-"b"
idAverageERL$conditionType[idAverageERL$condition %in% c("bbm","baseline")]<-"c"
idAverageERL$conditionType[idAverageERL$condition %in% c("abm")]<-"d"

idAverageERLtemp<-idAverageERL

supp.labs <- c("Late Ambiguous", "Early Ambiguous", "Late Bad Map", "Early Bad Map")
names(supp.labs) <- c("a", "b","c","d")


png("psychoOnlineLB.png", units="in", width=6, height=6, res=300)


ggplot(idAverageERLtemp, aes(step, SAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverageERLtemp,aes(ymin=SAnswer-sem,ymax=SAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
   scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#001219","#9B2226"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Baseline","Late Bad Map"))+
     # scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE, color=FALSE)+
  facet_wrap(~conditionType,labeller = labeller(conditionType = supp.labs))

dev.off()
```

