---
title: "badmapProjectPlots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##data wrangling packages (most part of the tidyverse)
library(stringr)
library(reshape2)
library(ggplot2)##plotting
library(plyr)
library(dplyr)
library(tidyr)
library(forcats)
library(scales)
library(modelbased)

#fonts
library(extrafont)
#font_import()
loadfonts(device = "win")




##analyses packages
library(lmerTest)
library(lme4)


options(scipen=1, digits=3)

```

#Load the data

##noun task and id task
```{r}
nounTask<-read.csv("nounResultsGood.csv", header=TRUE, stringsAsFactors = FALSE)

ddply(nounTask, .(Condition), summarize, NumSubjects = length(unique(Subject)))


idTask<-read.csv("idResultsGood.csv", header=TRUE, stringsAsFactors = FALSE)

sampleSize<-ddply(idTask, .(condition), summarize, NumSubjects = length(unique(subject)))

```



```{r}
SHres <- aggregate(sAnswer~step+condition, idTask, FUN="mean")

SHres_sd<-aggregate(sAnswer~step+condition, idTask, FUN="sd")

SHres$sd<-SHres_sd$sAnswer

idAverage<-merge(sampleSize, SHres)

idAverage$sem<-idAverage$sd/sqrt(idAverage$NumSubjects)

idAverage$conditionType[idAverage$condition %in% c("AAM","BAM","SSH")]<-"Ambiguous Conditions"
idAverage$conditionType[idAverage$condition %in% c("ABM","BBM")]<-"Bad Map Conditions"

idAverage$step<-factor(idAverage$step)

png("earlyAmbigExp1B.png", units="in", width=12, height=6, res=300)

ggplot(idAverage, aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","AAM","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)+
  facet_wrap(~conditionType)

dev.off()
```

```{r}

##EARLY 
SHres_phase <- aggregate(sAnswer~step+condition+phase, idTask, FUN="mean")

SHresphase_sd<-aggregate(sAnswer~step+condition+phase, idTask, FUN="sd")

SHres_phase$sd<-SHresphase_sd$sAnswer

idAveragePhase<-merge(sampleSize, SHres_phase)

idAveragePhase$sem<-idAveragePhase$sd/sqrt(idAveragePhase$NumSubjects)

idAveragePhase$conditionType[idAveragePhase$condition %in% c("AAM","BAM")]<-"Ambiguous Conditions"
idAveragePhase$conditionType[idAveragePhase$condition %in% c("ABM","BBM","SSH")]<-"Bad Map Conditions"

idAveragePhase$step<-factor(idAveragePhase$step)

idAveragePhaseEarly<-idAveragePhase[idAveragePhase$phase == "Early",]

png("earlyAmbigExp1BEARLY.png", units="in", width=12, height=6, res=300)

ggplot(idAveragePhaseEarly, aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","AAM","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#0A9396","#005F73","#BB3E03","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+
      theme_minimal(base_size = 14)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        plot.title = element_text(size=12),
        text = element_text(family="Arial"))+
  guides(linetype=FALSE)+
  facet_wrap(~conditionType)

dev.off()
```

```{r}

##EARLY 


idAveragePhaseLate<-idAveragePhase[idAveragePhase$phase == "Late",]

png("earlyBadmapExp1BLATE.png", units="in", width=12, height=6, res=300)

ggplot(idAveragePhaseLate, aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","ABM","BBM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005a9c","#bf2c37","#A5FFD6","#b9ae35","#001f23"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+
      theme_minimal(base_size = 14)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="right",
        legend.title=element_blank(),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        plot.title = element_text(size=12),
        text = element_text(family="Times New Roman"))+
  guides(linetype=FALSE)+
  facet_wrap(~conditionType)

dev.off()
```
```{r}

##plots for psychonomics poster

##all data
png("psychonomicsLateAmbig.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","BAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#CA6702","#001219"),labels=c("Late Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

#    scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+


png("psychonomicsEarlyAmbig.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","AAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","AAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#94D2BD","#001219"),labels=c("Early Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

png("psychonomicsLateBadmap.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","BBM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","BBM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#9B2226","#001219"),labels=c("Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()


png("psychonomicsEarlyBadmap.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","ABM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","ABM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005F73","#001219"),labels=c("Early Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

```


```{r}

##FIRST HALF DATA SET
png("psychonomicsLateAmbigERL.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","BAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#CA6702","#001219"),labels=c("Late Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

#    scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+


png("psychonomicsEarlyAmbigERL.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","AAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","AAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#94D2BD","#001219"),labels=c("Early Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

png("psychonomicsLateBadmapERL.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","BBM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","BBM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#9B2226","#001219"),labels=c("Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()


png("psychonomicsEarlyBadmapERL.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","ABM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseEarly[idAveragePhaseEarly$condition %in% c("SSH","ABM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005F73","#001219"),labels=c("Early Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()
```


```{r}

##plots for psychonomics poster

##all data
png("psychonomicsLateAmbig.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","BAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#CA6702","#001219"),labels=c("Late Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

#    scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+


png("psychonomicsEarlyAmbig.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","AAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","AAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#94D2BD","#001219"),labels=c("Early Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

png("psychonomicsLateBadmap.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","BBM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","BBM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#9B2226","#001219"),labels=c("Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()


png("psychonomicsEarlyBadmap.png", units="in", width=6, height=6, res=300)

ggplot(idAverage[idAverage$condition %in% c("SSH","ABM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAverage[idAverage$condition %in% c("SSH","ABM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005F73","#001219"),labels=c("Early Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

```


```{r}

##LATE HALF DATA SET
png("psychonomicsLateAmbigLT.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","BAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","BAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#CA6702","#001219"),labels=c("Late Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

#    scale_color_manual(values=c("#94D2BD","#005F73","#CA6702","#9B2226","#001219"),labels=c("Early Ambiguous","Early Bad Map","Late Ambiguous","Late Bad Map","Baseline"))+


png("psychonomicsEarlyAmbigLT.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","AAM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","AAM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#94D2BD","#001219"),labels=c("Early Ambiguous","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()

png("psychonomicsLateBadmapLT.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","BBM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","BBM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#9B2226","#001219"),labels=c("Late Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()


png("psychonomicsEarlyBadmapLT.png", units="in", width=6, height=6, res=300)

ggplot(idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","ABM"),], aes(step, sAnswer))+
  geom_line(aes(color=condition, group = condition), size=1)+
      geom_errorbar(data=idAveragePhaseLate[idAveragePhaseLate$condition %in% c("SSH","ABM"),],aes(ymin=sAnswer-sem,ymax=sAnswer+sem), width=.2,size=1,alpha=0.3, position=position_dodge(.9))+
  ylab("Percent 'S' answer")+
  xlab("Steps (from more S to more SH)")+
    scale_color_manual(values=c("#005F73","#001219"),labels=c("Early Bad Map","Baseline"))+
      theme_minimal(base_size = 16)+
    theme(plot.margin = unit(c(1,3,1,1),"lines"),
        legend.position="top",
        legend.title=element_blank(),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        plot.title = element_text(size=14),
        text = element_text(family="Arial"),
        panel.background = element_rect(fill="#FBF8EF", colour="#FBF8EF"),
        plot.background = element_rect(fill = "#FBF8EF"),
        panel.border = element_blank())+
  guides(linetype=FALSE)

dev.off()
```

